sensors:
  camera1:
    type: advanced_logical_camera
    pose:
      xyz: [1.051520, 3.151111, 1.5]
      rpy: [0, 0.856688, -0.606711]
    visualize_fov: true

  camera2:
    type: advanced_logical_camera
    pose:
      xyz: [6.310100, 1.913437, 1.5]
      rpy: [-2.465539, 1.201328, 1.328903]
    visualize_fov: true

  camera3:
    type: advanced_logical_camera
    pose:
      xyz: [4.191852, 0.944375, 1.5]
      rpy: [-0.654242, 1.291712, -1.044516]
    visualize_fov: true
  
  camera4:
    type: advanced_logical_camera
    pose:
      xyz: [1.893092, -2.736984, 1.5]
      rpy: [-2.465541, 1.201331, 1.328908]
    visualize_fov: true

  camera5:
    type: advanced_logical_camera
    pose:
      xyz: [5.942657, -1.809149, 1.5]
      rpy: [-2.625130, 1.075032, -0.675499]
    visualize_fov: true
  